spring:
  application:
    name: roundup-service
  datasource:
    url: jdbc:h2:mem:starlingdb # In-memory so data will be lost when restarted. In real world it would be an actual database
    driverClassName: org.h2.Driver
    username: starling-admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379

resilience4j:
  retry:
    instances:
      starlingApiRetry:
        max-attempts: 3  # Re-try 3 times
        wait-duration: 2s  # Wait 2 seconds before retrying
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException  # Timeouts
          - org.springframework.web.client.HttpServerErrorException  # 5xx errors
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException  # Don't retry 4xx errors